# Generated by Django 3.1.7 on 2021-09-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuais', '0003_auto_20210907_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivos',
            name='data',
            field=models.JSONField(),
        ),
    ]
