# Generated by Django 3.2.7 on 2021-09-07 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('BR', 'PORTUGUÊS'), ('EN', 'INGLÊS'), ('ES', 'ESPANHOL')], max_length=2)),
                ('image', models.ImageField(upload_to='images/')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='core.pessoa')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
